version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/arabakiralama
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arabakiralama
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
